### ISSUE TITLE
HTML has the nice <datalist> tag to provide an "autocomplete" feature. It would be great if a new form type supported this.

### ISSUE THREAD

**Issue by ToTru** [wtforms/flask-wtf#518] opened 2022-05-07 13:28 UTC
This would help to get rid of the scripting solutions.

**Comment by azmeuk** [comment] 2022-05-08 13:32
Duplicate of https://github.com/wtforms/wtforms/issues/653

**Closed** 2022-05-08 13:32 UTC
